language: ruby
rvm:
- 2.1.1
branches:
  only:
  - master
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id:
    secure: f9868I9zwwKEIYxSPKGZLsFkaIf7s8asEparimygAQHIB4yWHFMu6CUxRWPlrmrd+pkt4hbzS4c6CVCbD5WV/tQg5ORCBd4KKEYyKliBMbOh8P5ceCUCcA3zGZ/Wjua8guLrOoR43nbas2RwiMvIlBWX1pcafPV3b3iXfNrH8nA=
  secret_access_key:
    secure: RgyuJXEAnvNEm2aarbQFzGzNQHHyO1vLH/1Mk4Adj6vVpt6Y5TCJhA4hk5PpBpCg0+5svHCKaifRvFBGZHuqLBJY1dWOAhi/YtwX74cTBrcz41WYqEbHLrMO6k6bJmqkqD8fJ4h320yLaTz9uhLjhCj8SoiD3n86vJqPql+PCec=
  bucket: brooksgarrett.com
  region: us-east-1
  endpoint: www.brooksgarrett.com.s3-website-us-east-1.amazonaws.com
  local-dir: _site
