destination: _site/
disqus_shortname: brooksgarrett
markdown: redcarpet
name: Brooks Garrett
description: 'The blog of Brooks'
paginate: 5
permalink: /blog/:title/
highlighter: null
timezone: America/New_York
url: 'http://brooksgarrett.com/'

# Content Resources
navigation:
- text: About
  url: /about.html
- text: Speaking
  url: /speaking/
- text: WishList
  url: /wishlist.html
- text: Discovered
  url: /discovered/
- text: Projects
  url: /projects/
exclude: ['Gemfile','Gemfile.lock','README.md','Rakefile','s3_website.yml']
