destination: _site/
disqus_shortname: brooksgarrett
markdown: redcarpet
name: Brooks Garrett
description: 'The blog of Brooks Garrett'
paginate: 5
permalink: /blog/:title/
highlighter: pygments
timezone: America/New_York
url: 'http://brooksgarrett.com'

# Redcarpet renderer
redcarpet:
  extensions: ["strikethrough"]

# Content Resources
navigation:
- text: Blog
  url: /
- text: About
  url: /about.html
- text: Speaking
  url: /speaking/
- text: WishList
  url: /wishlist.html
- text: Discovered
  url: /discovered/
- text: Learning
  url: /learning/
exclude: ['Gemfile','Gemfile.lock','README.md','Rakefile','s3_website.yml','.sass-cache']

sass:
  style: :compressed
