steps:
  - name: 'us-central1-docker.pkg.dev/website-420415/build-images/hugo:latest'
    entrypoint: 'hugo'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gsutil
      - -m
      - rsync
      - -r
      - /workspace/public
      - gs://brooksgarrett.com
