name: Hugo site CI

on:
  release:
    types:
      - published
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the hugo container
      run: |
        docker run \
        -v ${{ github.workspace }}:/site brooksgarrett/hugo
    - uses: actions/upload-artifact@v2
      with:
        name: site
        path: ${{ github.workspace }}/public/